# Generated by Django 5.0.4 on 2024-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
