# Generated by Django 5.0.4 on 2024-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Descripción'),
        ),
    ]
