# Generated by Django 5.0.4 on 2024-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_alter_category_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Descripción'),
        ),
    ]
