# Generated by Django 5.0.4 on 2024-04-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_remove_product_cate_product_cat_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='male', max_length=10, verbose_name='Sexo'),
        ),
    ]
